use_frameworks!

platform :ios, '8.0'

target 'TIJK_Example' do
  pod 'TIJK', :path => '../'

  target 'TIJK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
